import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Raleway } from "@next/font/google";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const raleway = Raleway({
  subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {

  return (
    <main className={raleway.className}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Component {...pageProps} />
    </main>
  );
}
